[firebase]
type = "service_account"
project_id = "cse331-77111"
private_key_id = "74100017d081e3cbfc2afe8ddc9f78cc673989b6"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfVylm7yrW/CdK
ylfbaDGTHYMgO+uO8IhA+Cku+kT/JpBByWM+zRQApyvpEK48YT9oeH99pfOUcBMW
wgxXVUeXl/aOJvWv3Ph6IqJJKosxu96XGDWEPTWLePjZM9EuVhHps8M3IKn3/m5n
MLo+mQVyhwFPCtts0qTevSAlV4DxLJXLVgntV6cVk19agbXKtnvytivMIdBb7W4S
lqYGKG6w00gctSPfCNRdQSbKRd+pyyneBJPtRnntnWrkhSTv5LW2iQ7S+U9ra02E
l8bpeu4ee5XFmijuwdE+LJM/339fkxDPsNKA3BsDUAfKGC+xFZnkREYcOZx7TIA2
EKHdFMNzAgMBAAECggEAHVum4jNQ1lmRN8N+WouhDrUSUt8XcLe6sxXGKMSt78EA
NU7QvWJ1vAURHxkWsUNNtob1HoZ0EbZwnfHU6kZpMXIrWFevTt7M3VwCQK7ZBKnT
wk0QlzPb6L26Q/K7KOls1X1si3y2NF4po1OkDSKOkWJ0iEa81RkejXeVM6wissy0
wMqCdMfs9RzvtBXVH6lGvvrZEbs7+a29JwIjIID4ZvfrdI09/2w1QFKwxB/ilWET
ce7s55s3gbVhmxiyZF+yg0Ml9n7uapwcq2/rVEB7/H2UmURx/IRh6KsiED8xJ1+2
sqKNd2Hs4uNRVxW5o77cLVBXkgKYKO2ZzTtcKvwMkQKBgQDNqiFVRme/lVyj2z8l
LUfELjgdDujpBUIRICw3XYq9c9RXaX941D/NRAI/QZBCh2pH3fIwR8NwaCG+dpl+
md+ApfPqmHdQFXls67p3pSbAhq266jfQjtD9tMesdB0ed24R2Y+H2PHz+oUQ9nV2
O4dwcwR+fZlzIcf/wasyR2mPywKBgQDGVpruSn5Q2NB2qFX6/YGT9DPwPXWr5K24
ToGJzabaY+9ZQKWTXi9Zjv8RHN5DEUw8p6KkoxI5ph0RnF13daD+TcvrcGcNkjqR
rQ5v2VUK0vwc/E7goh80ZvaOkjxsV+AtMWxnbUPOGdARmEWdwszwbf6Rh2LS7Izn
LR2ZV8zV+QKBgHJmq4oK0tUwGUsQPyzH5j7LUu1fCNHt2dU65z2Y6/78emZxSbYF
osPki7dyGfPX7ZeybvDKSn2xfuu6fyF8KGYgafDaBKxodZXP/nZlSIwZnnP1qzx4
5OnrcJKOOFBlMLX/Jibz14rWlMRdw/MTpAA6CoruBLiVVvH+YeNi8+ZHAoGBAJxq
zrLg8u+FnhoGNhDEfr2VWKS9g6C1rz9sQoLQOid/qtKDxlELdWI3APeZAbx41tv7
BKy8onHujHxICfpdPUNxTUH3mn48dY5PodQZ3RS1QfkGDprfoKZuEUJtF9QGFZju
omSK6m+PMeW+ZiC98WwoAxz4XbqkrZbfoLk/Yh7ZAoGATkdq1j5piwMpM6IZRzMI
4h6eK/TGYQp3FayJtYNOwJUPHhH6vODCs2Nq+gbjmQ9bsQ2OeHwrRGg2wCs485qK
wdZ89S/CRenGGB3nvbo43CfISR0udmJE6ZMA9wPzgXxHsQ2SHchsNDbxYeqvj9Fv
SuxwJUfEa/qfnEmPa3ZGsL0=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@cse331-77111.iam.gserviceaccount.com"
client_id = "114000379991722929475"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40cse331-77111.iam.gserviceaccount.com"
universe_domain = "googleapis.com"